CREATE TABLE [FINAL].[K12_StudentEnrollment2012]
(
[FINAL_K12_StudentEnrollment2012ID] [int] NOT NULL IDENTITY(1, 1),
[RAW_K12_StudentEnrollment2012ID] [int] NOT NULL,
[SchoolYear] [smallint] NOT NULL,
[DistrictCode] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DistrictName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResidentDistrictCode] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ResidentDistrictName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolCode] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SchoolName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationID] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PrimarySchoolFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DistrictStudentID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StudentLastName] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StudentFirstName] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StudentMiddleName] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [date] NOT NULL,
[Gender] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GradeLevelSortOrder] [smallint] NULL,
[GradeLevel] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DateEnrolledinDistrict] [date] NOT NULL,
[DateExitedDistrict] [date] NULL,
[DateEnrolledinSchool] [date] NOT NULL,
[DateExitedSchool] [date] NULL,
[WithdrawalCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WithdrawalType] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthCountryCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthCountry] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FederalEthRaceRollupCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FederalEthRaceRollupName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryLanguageCode] [smallint] NULL,
[PrimaryLanguage] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LanguageSpokenatHomeCode] [smallint] NULL,
[LanguageSpokenatHome] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GradReqYear] [smallint] NULL,
[ExpectedGradYear] [smallint] NULL,
[CumulativeGPA] [numeric] (4, 3) NULL,
[CumulativeCreditsAttempted] [numeric] (6, 2) NULL,
[CumulativeCreditsEarned] [numeric] (6, 2) NULL,
[NumDaysPresent] [tinyint] NULL,
[NumUnexcusedAbsences] [tinyint] NULL,
[DisabilityFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApprvdPrivateSchoolAttendPartTimeFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeBasedAttendPartTimeFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F1VisaForeignExchgFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreeReducedLunchFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomelessFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FosterCareFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[S504Flag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GiftedFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MigrantFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilingualFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpecialEdFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubmitDate] [date] NOT NULL,
[ExtractDate] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [FINAL].[K12_StudentEnrollment2012] ADD CONSTRAINT [PK_FINAL_K12_StudentEnrollment2012ID] PRIMARY KEY CLUSTERED  ([FINAL_K12_StudentEnrollment2012ID]) ON [PRIMARY]
GO
